### ISSUE TITLE
5/22 Check-in broke the build Step5Project.cs @ line 350

### ISSUE THREAD

**Issue by ledbette** [dotnetprojects/DotNetSiemensPLCToolBoxLibrary#101]

**Comment by ledbette** [comment]
VS2015.  It doesn't like this line:
    tmpBlk.Assembler = (bits & 0b00001000) > 0; // -> Assembler

Is that supposed to be 0x00001000 or 0x0b00001000?

Wade      From: Jochen Kühner <notifications@github.com>
 To: dotnetprojects/DotNetSiemensPLCToolBoxLibrary <DotNetSiemensPLCToolBoxLibrary@noreply.github.com> 
Cc: ledbette <wade.ledbetter@sbcglobal.net>; Author <author@noreply.github.com>
 Sent: Friday, July 6, 2018 6:28 AM
 Subject: Re: [dotnetprojects/DotNetSiemensPLCToolBoxLibrary] 5/22 Check-in broke the build Step5Project.cs @ line 350 (#101)
   
wich vs version do you use? this works with vs2017—

**Comment by jogibear9988** [comment]
vs2015 does not support this syntax

**Comment by ledbette** [comment]
Thought this might have been a typo, but I see the 0b prefix is binary literal, new to C#7.0.  So 0x08 would be the hex literal substitution to get it to build in VS2015.

**Comment by jogibear9988** [comment]
Why do you need to build it in Vs2015? Can't you use the Nuget Package?
