### ISSUE TITLE
DotNetSiemens lib mit Raspberry Pi Linux oder Win IOT (Dotnet Core)

### ISSUE THREAD

**Issue by Nick135** [dotnetprojects/DotNetSiemensPLCToolBoxLibrary#102]
Hallo Jochen,

hast du deine Lib schon mal auf nem Raspberry laufen lassen?

In der Lib sind ja Pragma für das IPhone drin. Kann man das eventuell als Basis für den Raspberry hernehmen?

**Comment by jogibear9988** [comment]
auf dem Iphone hat ich das vor jahren mal am laufen! Sollte eigentlich gehn...

**Comment by Nick135** [comment]
Wenn ich die Compileranweisung "IPHONE" verwende, wird ja anstelle der libnodave_jfkmod.dll __Internal aufgerufen. Wo finde ich die dll?

`
#if !IPHONE
            [DllImport("libnodave_jfkmod.dll", EntryPoint = "daveDisconnectAdapter")]
#else
            [DllImport("__Internal", EntryPoint = "daveDisconnectAdapter")]
#endif
`

**Comment by jogibear9988** [comment]
ich hab damals die libnodave mit dem Makefile: https://github.com/dotnetprojects/DotNetSiemensPLCToolBoxLibrary/blob/master/externalDlls/libnodave/libnodave_patches/Makefile.Iphone übersetzt.

und dann muss man später wenn man in Xamarin übersetzt die statische lib dazulinken (puh, wie das ging weiß ich grad nimmer).

Aber an dem Makefile muss man bestimmt etwas anpassen, da iPhone apps ja jetzt 64 bit sind!

**Comment by Nick135** [comment]
Für den Raspi hat es funktioniert die Makefile auf dem Raspi zu kompilieren und die libnodave.so in "libnodave_jfkmod.dll" umzubenennen.

Für die Siemens SIMATIC IOT2000 Box bring ich es nicht zum laufen.
[https://www.sps-forum.de/hochsprachen-opc/93763-libnodave-kompilieren-auf-simatic-iot2000.html#post703621](url)
