### ISSUE TITLE
Frage zu "Bugfix PlcConnection"

### ISSUE THREAD

**Issue by Nick135** [dotnetprojects/DotNetSiemensPLCToolBoxLibrary#103]
> https://github.com/dotnetprojects/DotNetSiemensPLCToolBoxLibrary/commit/6d41c3c7ed21c388114aa192c881353165f1c7f6
>

Aus welchem Grund wurde dies geändert? Wenn keine Verbindung besteht ist es doch nur logisch wenn die lib diese schließt.
AutoDisconnect ist per default false und somit nicht kompatibel mit alten Projekten.

**Comment by jogibear9988** [comment]
Weiß leider den Grund nicht mehr. ;-(
Habs als default gemacht
