### ISSUE TITLE
Cannot build the solution

### ISSUE THREAD

**Issue by yuriqdev** [dotnetprojects/DotNetSiemensPLCToolBoxLibrary#104]
I Cannot build the solution with VS 2015
Error	 The name "PLCTag" does not exist in the namespace "clr-namespace:DotNetSiemensPLCToolBoxLibrary.Communication;assembly=DotNetSiemensPLCToolBoxLibrary".

Error	 Cannot find the type 'ProtokollerConfiguration'. Note that type names are case sensitive.	JFK-ProtokollerConfigurationTool

Error	CS0006	Metadata file 'C:\Users\User\Source\Repos\dotnetprojects\DotNetSiemensPLCToolBoxLibrary\compiled\DotNetSiemensPLCToolBoxLibrary.dll' could not be found

**Comment by jogibear9988** [comment]
you need to use vs2017
