### ISSUE TITLE
-10 error return Serial Port data receive

### ISSUE THREAD

**Issue by DavoodRm** [dotnetprojects/DotNetSiemensPLCToolBoxLibrary#106]
hi
when i try to connect to plc s7 300 with serial port and cp340 after successfully connect i receive -10 error when trying receive data trough serial port.
any advice and suggestions will be greatly appreciated.

**Comment by jogibear9988** [comment]
it is not possible to connect to a s7 via a cp340

**Comment by dramezani** [comment]
Thank you for the answer
I meant to connect s7 to reading the data sent by s7 from the serial port
The cp340 has three protocols, one of which is ascii and sends data to the serial port

**Comment by jogibear9988** [comment]
then you don‘t need my lib, use serial port class
