### ISSUE TITLE
Kommunikation per COM Port (MPI)

### ISSUE THREAD

**Issue by Nick135** [dotnetprojects/DotNetSiemensPLCToolBoxLibrary#108]
Hallo Jochen,
hast du mit deiner Lib schon ne Verbindung per COM/MPI zur S7 aufgebaut? Was ist zu beachten?

**Comment by jogibear9988** [comment]
vor jahren mal, glaube ich. hab schon ewig keinen seriell mpi adapter mehr gesehen bzw. probiert
