### ISSUE TITLE
PLCGetBlockInMC7 returns null for a valid DB

### ISSUE THREAD

**Issue by marcelom9** [dotnetprojects/DotNetSiemensPLCToolBoxLibrary#116]
Sometimes a perfectly working DB starts to return NULL to PLCGetBlockInMC7 calls.
The connection is ok since several other DBs return their correct structure.
More over, the function PLCListBlocks(PLCBlockType.DB) returns the name of the DB as a valid DB name.
So, it works for months and suddenly it istarts happening this issue, not always same plc nor same DB. Some more info, Step7 can connect to the plc and set the DB online with no problem.. 
I also tried to disconnect and reconnect the plc connection but nothing changes, it keeps returning NULL.
The only solution I found up to now to is re-upload the DB from STEP7. 
Have someone experimented this behaviour?
Thanks in advance.

**Comment by jogibear9988** [comment]
maybe you can record via wireshark wehn this happens?
