### ISSUE TITLE
PLC Programmer commands Forces

### ISSUE THREAD

**Issue by Nick135** [dotnetprojects/DotNetSiemensPLCToolBoxLibrary#119]
Im Step7 Manager gibt es bei den Variablentabellen die Möglichkeit die Forcewerte anzuzeigen und auch selbst Ein und Ausgänge zu Forcen.

Ist dazu schon was in der Lib implementiert?

**Comment by jogibear9988** [comment]
wüsste nicht das ich forcen implementiert habe
