### ISSUE TITLE
PLCNckTag 

### ISSUE THREAD

**Issue by r0si** [dotnetprojects/DotNetSiemensPLCToolBoxLibrary#131]
Moin,

Woher bekomme ich die Werte wie z.B 'Spalte', 'Bereich', 'Zeile' für den PLCNckTag von NC Variablen einer bspw. 840Dsl her ?
Im Siemens Listenhandbuch "NC-Variable und Nahstellensignale" finde ich nicht viel oder habe falsch geschaut?

Grüsse

**Comment by Nick135** [comment]
Servus,
dafür gibt es den NC-VAR-SELECTOR. Dieser ist bei der Toolbox für die NC Stände dabei.
