### ISSUE TITLE
S5 Siemens PLC - Reading Outputs Doesn't Work

### ISSUE THREAD

**Issue by InnovationUnplugged** [dotnetprojects/DotNetSiemensPLCToolBoxLibrary#135]
The issue that i have is that i can't read digital outputs on a S5. After calling ReadValues("A32.0") i always get false even though the status leds on the PLC are changing from False -> True. Is that a known issue? Is there a code snippet that solves that problem?

**Comment by jogibear9988** [comment]
I‘ve never tested on a S5 (I don‘t have one). I only implemnted it cause it was supported in libnodave

**Comment by jogibear9988** [comment]
@InnovationUnplugged how do you connect your S5?

**Comment by jogibear9988** [comment]
no answers

**Comment by InnovationUnplugged** [comment]
Then how about this: Since i have the S5 PLC and i have developers background - i can contribute by testing the code on my PLC. Currently i connect to the PLC using the PG port and an active tty > RS232 converter. As far a the code goes - i can start and stop the PLC, but when i try to read out any of the digital Outs i always get a False. So what do you say ? Do we try to tackle this issue?

**Comment by InnovationUnplugged** [comment]
i can also share code snippets of what i am trying to do.... i have to say that enabling this Digita output readouts will be a great added value to this project from my point of view.... but i need somebody on your side to support me with this.... I can offer quite a lot of my time + PLC + testing approach.

**Comment by InnovationUnplugged** [comment]
i can also share code snippets of what i am trying to do.... i have to say that enabling this Digita output readouts will be a great added value to this project from my point of view.... but i need somebody on your side to support me with this.... I can offer quite a lot of my time + PLC + testing approach.

**Comment by jogibear9988** [comment]
@InnovationUnplugged sorry I haven't seen your answers here :-(
