### ISSUE TITLE
TIA Openness Integration: Limited to S7-1500 devices

### ISSUE THREAD

**Issue by thomasb454** [dotnetprojects/DotNetSiemensPLCToolBoxLibrary#149]
Hi

I'm just curious as to the reason the TIA Openness Integration is limited to S7-1500 devices?
(https://github.com/dotnetprojects/DotNetSiemensPLCToolBoxLibrary/blob/master/DotNetSiemensPLCToolBoxLibrary.TIAV15_1/Step7ProjectV15_1Tia.cs#L861)

In a local copy, I have omitted this check and to my knowledge, everything is working correctly. Have I missed something?

Thank you
Tom

**Comment by jogibear9988** [comment]
Maybe you could create a pull req? Don't know anymore why I did thsi.

**Comment by thomasb454** [comment]
I certainly will when I get some time :)

**Comment by thomasb454** [comment]
https://github.com/dotnetprojects/DotNetSiemensPLCToolBoxLibrary/pull/153
