### ISSUE TITLE
Read DB Array Size 1024 with ReadValues not possible 

### ISSUE THREAD

**Issue by Nick135** [dotnetprojects/DotNetSiemensPLCToolBoxLibrary#154]
Das lesen eines Byte Arrays der Größe 1024 führt bei ReadValues zu einem Exception. Mit ReadValue funktioniert es.

> Operation failed due to error from PLC 255: no message defined!

> at DotNetSiemensPLCToolBoxLibrary.Communication.PLCConnection.ReadValues(IEnumerable`1 valueList, Boolean useReadOptimization) in \DotNetSiemensPLCToolBoxLibrary-master\LibNoDaveConnectionLibrary\Communication\PLCConnection.cs:line 2925

> at DotNetSiemensPLCToolBoxLibrary.Communication.PLCConnection.ReadValues(IEnumerable`1 valueList) in \DotNetSiemensPLCToolBoxLibrary-master\LibNoDaveConnectionLibrary\Communication\PLCConnection.cs:line 2597

	`string ip = "192.168.214.1";

	 string plcAddress = "P#DB123.DBX0.0 Byte 1024";	 // Fehler bei ReadValues
	 //plcAddress = "P#DB123.DBX0.0 Byte 1030";	 	 // Funktioniert
	 using (var myConn = new PLCConnection("Debug"))
	 {
		  myConn.Configuration.CpuIP = ip;
		  myConn.Connect();
		  try
		  {
				var a = myConn.ReadValue(plcAddress); // Funktioniert bei beiden Adressen
		  }
		  catch (Exception) { }
		  try
		  {
				var tag = new PLCTag(plcAddress);
				myConn.ReadValue(tag);                         // Funktioniert bei beiden Adressen
		  }
		  catch (Exception) { }
		  try
		  {
				var tags = new List<PLCTag>();
				tags.Add(new PLCTag(plcAddress));
				myConn.ReadValues(tags);                     // Exception bei 1024 Byte
		  }
		  catch (Exception) { }
	 }`

**Comment by Nick135** [comment]
Hab den Bug gefunden.

'(maxReadSize - HeaderTagSize)' hinzugefügt.
![image](https://user-images.githubusercontent.com/14072733/97780880-b66c0700-1b87-11eb-9a13-a97e512cc218.png)

**Comment by Nick135** [comment]
Was mir noch aufgefallen ist, dass die ReadValue Methode 222 Bytes liest und die ReadValues nur 204 pro PDU.

![image](https://user-images.githubusercontent.com/14072733/97780957-427e2e80-1b88-11eb-8b28-8121d8a588b1.png)

**Comment by jogibear9988** [comment]
Ich schau es mir an, kann aber bissl dauern.
Problem, wir nutzen meine lib Produktiv, und das ist für mich die kritischste stelle... wenn da was falsch ist stimmen alle werte nicht.
Muss n test für den Fehler machen und prüfen ob sich eine Änderung noch anders auswirkt

**Comment by jogibear9988** [comment]
Ja, redvalues nutzt einen anderen request mit einem größeren header, die kann dann nur weniger lesen.

**Comment by jogibear9988** [comment]
danke für den hinweis, habs gefixt
