### ISSUE TITLE
Is there an example how to read the DB symbols & structrure from the SUBBLK.DBT file in the S7 Project?

### ISSUE THREAD

**Issue by mut9bu** [dotnetprojects/DotNetSiemensPLCToolBoxLibrary#184]
Hello
I have looked to your examples but couldn't find one how to get the DB symbols and structure from the SUBBLK.DBT file in the S7 Project? Can you help me to find an example for it?

**Comment by jogibear9988** [comment]
Many of the code to parse the subblk.dbf is in the file DotNetSiemensPLCToolBoxLibrary\LibNoDaveConnectionLibrary\DataTypes\Projectfolders\Step7V5\BlocksOfflineFolder.cs
