### ISSUE TITLE
Network Interface Missing - CPU315-2PN/DP

### ISSUE THREAD

**Issue by arthurhauer** [dotnetprojects/DotNetSiemensPLCToolBoxLibrary#187]
When parsing a project with a CPU 315-2PN/DP station (6ES7 315-2EAH14-0AB0 / V3.1), the onboard PN interface is not included in the Project object.

**Comment by jogibear9988** [comment]
sorry, I've no time at the moment tolook for this. Maybe you could help with a pull req?

I think code for network interfaces is here: https://github.com/dotnetprojects/DotNetSiemensPLCToolBoxLibrary/blob/master/LibNoDaveConnectionLibrary/Projectfiles/Step7ProjectV5.cs#L1304

**Comment by jogibear9988** [comment]
https://www.sps-forum.de/threads/s7-projektdateien-ip-adressen-auslesen.73225/
