### ISSUE TITLE
Is it possible to read *.PG files from the S7-Project (in SDB folder) with DotNetSiemensPLCToolBoxLibrary ?

### ISSUE THREAD

**Issue by mut9bu** [dotnetprojects/DotNetSiemensPLCToolBoxLibrary#216]
Hello I have seen that it is possible parse DBF files with DotNetSiemensPLCToolBoxLibrary . But in my case I need to parse data from a *.PG file in the S7 Project. Is that possible? For testing I have tried to open the PG file with a online DBF reader but without succes. But when I opened the *.PG file with the online FILExt app, I could see the content without any problem.
Does anyone know how the *.PG file is encoded and if its possible to read it with DotNetSiemensPLCToolBoxLibrary?

**Comment by jogibear9988** [comment]
What information is inside of the PG files?

**Comment by jogibear9988** [comment]
I don't know what the contes of those files is, you need to analyze them.
But if they are from a third party software, they have nothing to do with this library

**Comment by mut9bu** [comment]
Hello, for correct understanding: PG files are part of the S7-Project structure, not of the 3. part library:

**Comment by jogibear9988** [comment]
Here are also some infos about the SDBs....

https://www.sps-forum.de/threads/liste-von-systembausteinen-welcher-ist-f%C3%BCr-was-zust%C3%A4ndig.86031/#post-647381

https://www.sps-forum.de/threads/mc7-code-in-awl-umzuwandeln.27703/page-4#post-606043

https://www.sps-forum.de/threads/globaldaten-auslesen.41518/#post-301946

**Comment by jogibear9988** [comment]
@mut9bu 
ask process informatik, maybe they can help you.

**Comment by mut9bu** [comment]
> And one more, you could ask "Deltalogic" for help. Years ago they had their own Programming Software for Siemens PLCs, wich they stopped developing. Maybe they share some information (maybe for some money).
> 
> And also https://www.mhj-online.de/ has a step7 software, so they also need to understand all of the files.
> 
> And one more: https://www.process-informatik.de/ has also a S7 programming software, so they also know the files

Thank you so much Jochen! I will follow your suggestioons 👍

**Comment by jogibear9988** [comment]
If you get some information, it would be nice if you add it to the toolbox (or at least leave some informations)

**Comment by mut9bu** [comment]
> If you get some information, it would be nice if you add it to the toolbox (or at least leave some informations)

Definitly, I will do it, thank you again 👍
