### ISSUE TITLE
Issue by loading projects with s7 programs without a PLC

### ISSUE THREAD

**Issue by impoetk** [dotnetprojects/DotNetSiemensPLCToolBoxLibrary#40]
I have found that an exception is thrown when opening projects with offline foldes that have no CPU as parent.

im not sure why, but the exception is thrown in the linq expression in the Step7ProjectV5.cs LoadProject Method

             foreach(var dp in DPlist)
            {
                var dpf = DPFolders.FirstOrDefault(x =>  x.IdTobjId.Any(y => y == dp.TobjID));
                if ( dpf != null)
                {
                    if (dpf.TobjId == null) dpf.TobjId = new List<int>();
                    dpf.TobjId.Add(dp.addr);
                }
            }

to fix it i have modified the linq to the following

                var dpf = DPFolders.FirstOrDefault(x => x.IdTobjId != null && x.IdTobjId.Any(y => y == dp.TobjID));

**Comment by jogibear9988** [comment]
could you create a pull req?

Von meinem iPhone gesendet

**Comment by jogibear9988** [comment]
closed via #41
