### ISSUE TITLE
Project in TIA Portal V13 Upd6 Problem with opening

### ISSUE THREAD

**Issue by PawelStasiolek** [dotnetprojects/DotNetSiemensPLCToolBoxLibrary#42]
At this moment:
tiaPortal = new TiaPortal(TiaPortalMode.WithoutUserInterface);
When i wont to open project i have error "Connection to TiaPortal failed."
When we look inside in the library Siemens.Engineering.dll

string fullPath = Path.GetFullPath(Path.Combine(ApplicationEntryPoint.Loaction, "../../bin/Siemens.Automation.Portal.exe"));

So we must move project to C:\Program Files (x86)\Siemens\Automation\Portal V13\Bin\PublicAPI\V13 SP1 ?? and from there start ?

Also is another problem with TIA.
When Im trying to "PLCListBlocks"
at this point :
int ret = _dc.ListBlocksOfType(Helper.GetPLCBlockTypeForBlockList(myBlk), blocks);
I have error: Error: no message defined! 
ret is: -33028

**Comment by jogibear9988** [comment]
I've to try...

**Comment by jogibear9988** [comment]
much of the code has changed, if this is still an issue, reopen
