### ISSUE TITLE
How we read real value from this code

### ISSUE THREAD

**Issue by ramanandmittal** [dotnetprojects/DotNetSiemensPLCToolBoxLibrary#47]
Hi Experts,

Please guide me how we can read real, int values from bytes.

**Comment by jogibear9988** [comment]
?? what do you want?

**Comment by ramanandmittal** [comment]
From this code i can read bytes but i need values in real form like in byte reading value came 66 but its double or real values 1440. So how i can convert the same.
Please guide.

**Comment by jogibear9988** [comment]
I don't understand your question! Wich Code? WIth so spare information I cannot help you!
