### ISSUE TITLE
how to read a long DB (with PLCConnect and PLCTag)

### ISSUE THREAD

**Issue by SevenMag** [dotnetprojects/DotNetSiemensPLCToolBoxLibrary#6]
I'm read more DBs different lengths. But read PLCTag("P#DB888.DBX0.0 BYTE 500") throws error because 500 > MaxPDULen.
how to read a long DB another method?

**Comment by jogibear9988** [comment]
testcomment

**Comment by SevenMag** [comment]
test ok

**Comment by jogibear9988** [comment]
I think this should be fixed, cause I updated libnodave with the fixes from original project
