### ISSUE TITLE
MEF - SharpZipLib dependency

### ISSUE THREAD

**Issue by MichaelKeidler** [dotnetprojects/DotNetSiemensPLCToolBoxLibrary#70]
when creating a dll with a dependency to DotNetSiemensPLCToolBoxLibrary and using the
Managed Extensibility Framework (MEF) to lazy load it into an application i get an error that there are dependecies to a SharpZipLib dll (ICSharpCode.SharpZipLib.dll) which is not in there.

Maybe it is missing in the nuget package or an obsolete reference

**Comment by jogibear9988** [comment]
I need to fix the nuget package, I need to add the sharpzoplib dependency

**Comment by jogibear9988** [comment]
fixed
