### ISSUE TITLE
What do the S7ConvertingOptions do exactly?

### ISSUE THREAD

**Issue by mindfuucker** [dotnetprojects/DotNetSiemensPLCToolBoxLibrary#81]
Hi,

I'm looking for some guidance in using the toolbox. I use it to convert S7 project data directly to SCADA-objects. 

I am trying to find the Called FB of an UDT-instance and I think using the S7ConvertingOptions might help me filter the addresses. (I have an UDT80 in DB18, 20.0 and I want to know that it is used in FC201)

Could you elaborate what the S7ConvertingOptions  do? Or do you know another way of finding the FC?

**Comment by jogibear9988** [comment]
The Converting Options will not help you!

Atm. there is no easy way of doing this!
