### ISSUE TITLE
Tia openness tags

### ISSUE THREAD

**Issue by impoetk** [dotnetprojects/DotNetSiemensPLCToolBoxLibrary#92]
Hi

I've reading through the code to find where the tags are parsed, so far i've only seen the tag tables but if they dont have a constant nothing else gets parsed

Am I missing something? are they parsed somewhere else?
https://github.com/dotnetprojects/DotNetSiemensPLCToolBoxLibrary/blob/4bf9b492d3ad1255f5ce405caf75243cbd680a37/DotNetSiemensPLCToolBoxLibrary.TIAV15/Step7ProjectV15Tia.cs#L219-L225

**Comment by impoetk** [comment]
I looked even more and did not found anything, im implementing it in my fork, maybe you can take a look when i finish

**Comment by jogibear9988** [comment]
think this can now be closed?

**Comment by impoetk** [comment]
ok for me
